version: '3.9'
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto-test/config:/mosquitto/config
      - ./mosquitto-test/log:/mosquitto/log
      - ./mosquitto-test/data/:/mosquitto/data
    restart: always
    ports:
      - "1883:1883"
